### ISSUE TITLE
Which account to use for PowerApps SharePoint Connnection

### ISSUE THREAD

**Issue by FritsH** [OfficeDev/microsoft-teams-apps-requestateam#101]
In the deployment guide, Step 3.4 (and 4,4) I need to setup a connection wth sharepoint to allow the powerapp to access data in SP. It askes for an authorisation, in the screenshot an admin account is used here. Which account can/needs to be used here? Does this have to be the service account or the account (global admin) used to setup the application?

Many thanx in advance.

**Comment by alexc-MSFT** [comment]
@FritsH the key is to make the connection WITH the account used to import the Power App not another account (otherwise any requests get created as that user). So you could import the Power App as the service account and make the connection as that user. Then you can share the app with whomever you need.

Thanks
