### ISSUE TITLE
Edting PowerApp

### ISSUE THREAD

**Issue by AlanPutt** [OfficeDev/microsoft-teams-apps-requestateam#132]
Hi there

Firstly, many thanks for creating this app!

I'm really new to PowerApps so excuse my lack of knowledge.

When I try to edit the App layout to bespoke it to our needs I see the first screen, options to Create from Template or Blank but subsequent screens are blank.

![image](https://user-images.githubusercontent.com/69569836/90700960-845a4100-e2ca-11ea-9e43-2e377f13d489.png)

![image](https://user-images.githubusercontent.com/69569836/90701005-9fc54c00-e2ca-11ea-8288-0770f76202a0.png)

But when I play the app I see text like, Privacy, Team name Description etc....  Is this pulled from somewhere else?

![image](https://user-images.githubusercontent.com/69569836/90701167-13ffef80-e2cb-11ea-8c76-f2db0dd68af1.png)

Many thanks

Alan

**Comment by loflet** [comment]
Hi @AlanPutt, I understand the Powerapps can be very overwhelming for the start. Let me try to explain what you are facing in simple terms. the subsequent screen is blank because the visibility parameter of the items is bound to a variable which gets populated on click of the buttons or some other controls such as "Build New" button. 

What you can do to see the content on the next screen in edit mode: - 
Press ALT and click on the button like "Build new" present on the first screen. This will take you to the next screen with items visible to you.

This PowerApp structure can be complex for you if you haven't worked on PowerApp at all and will recommend you to refer https://docs.microsoft.com/en-us/learn/modules/get-started-with-powerapps/ if you are interested in learning PowerApp.

Thanks,
Sanket

**Comment by AlanPutt** [comment]
Many thanks, Sanket
