### ISSUE TITLE
Error creating Group in logic app

### ISSUE THREAD

**Issue by sthieu** [OfficeDev/microsoft-teams-apps-requestateam#148]
The ProcessTeamRequest logic App is failing on the Create Group steps. Have tried this a few times with the same result.

![image](https://user-images.githubusercontent.com/15640508/93425762-bf25b800-f90e-11ea-9171-0f360fd016b6.png)

Here's the raw output from the failed step

`{
    "statusCode": 400,
    "headers": {
        "request-id": "b64eb4c2-2baf-4284-83f0-f4893f0b8c2e",
        "client-request-id": "b64eb4c2-2baf-4284-83f0-f4893f0b8c2e",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"Australia Southeast\",\"Slice\":\"SliceC\",\"Ring\":\"4\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AGSFE_IN_1\"}}",
        "Strict-Transport-Security": "max-age=31536000",
        "Cache-Control": "private",
        "Date": "Thu, 17 Sep 2020 05:38:05 GMT",
        "Content-Length": "731",
        "Content-Type": "application/json"
    },
    "body": {
        "error": {
            "code": "Request_BadRequest",
            "message": "Object '[ResourceType=User,Id=cc65472e-f067-45dd-9d3d-5e2bf13ca892,ChangedProperties=[],NonDefaultProperties=[INTERNAL_SingleResourceQuery]]' referenced from '[ResourceType=Group,Id=744f69b4-e192-435a-8a31-0f03cd9b4303,ChangedProperties=[DisplayName,Description,GroupType,MailEnabled,MailNickname,SecurityEnabled,IsPublic,CreatedByAppId],NonDefaultProperties=[INTERNAL_EnableF14M1SchemaEnumTypes,visibility]]' can only be present once as an add/remove change.",
            "innerError": {
                "date": "2020-09-17T05:38:05",
                "request-id": "b64eb4c2-2baf-4284-83f0-f4893f0b8c2e",
                "client-request-id": "b64eb4c2-2baf-4284-83f0-f4893f0b8c2e"
            }
        }
    }
}`

**Comment by joostvdlinden** [comment]
I am facing the exact same issue here...

**Comment by joostvdlinden** [comment]
I found the solution to the issue.
The design of this solution takes into account that there will be two user accounts associated:
- An global admin account
- A service account

If you use the same user account for both of them, this will result in the error above.
If you use just only one user account instead of two, simply remove the highlighted action cards from the Logic App workflow.
![2020-10-02 16_34_51-History version (Readonly) - Microsoft Azure and 5 more pages -  InPrivate  - Mi](https://user-images.githubusercontent.com/47981540/94935492-6c7efb00-04cd-11eb-948c-a3ef5711159e.png)

**Comment by sthieu** [comment]
Thanks @joostvdlinden for identifying the issue and also providing a solution.
