### ISSUE TITLE
Problems with starting after update to PowerApps >3.2.1103.27

### ISSUE THREAD

**Issue by J-a-k-o-b** [OfficeDev/microsoft-teams-apps-requestateam#326]
Hi,
it seems that a change in PowerApps leads to errors starting the app. The App is using the OnStart Method to declare global vars etc. (See https://powerapps.microsoft.com/en-us/blog/app-startscreen-a-new-declarative-alternative-to-navigate-in-app-onstart/)
The OnStart is depreceated and we should use StartScreen instead. 
After a little unrelated adjustment was made by me in the app, the app was stored with a newer PowerApps Version (3.2.1103.27) which leads to a non-usable app like this:
![image](https://user-images.githubusercontent.com/46894290/139683743-9db7d1d4-e693-4580-adea-6d52b318096d.png)

I've now enabled the Retired Feature 'Enable Navigate function in App.Onstart' again and disabled the preview feature 'Use non-blockling OnStart rule'.
Now the global vars will be defined again while starting the app. 
Copy/Paste the functions from App.OnStart -> App.StartScreen was not successful. Need to read and understand the posted blog article to be able to transform the app

**Comment by alexc-MSFT** [comment]
@J-a-k-o-b so the OnStart is not deprecated as a whole, what is deprecated is the use of the 'Navigate' function within OnStart.

The RaT Power App doesn't use Navigate as the first screen in the list is the one we navigate to, so we have no need to use that function.

I've just tested by updating the app and saved a copy to get the version updated and it's working just fine so I don't think you are running into this issue.

I think your issue is something else, what happens if you right click App and run the OnStart?

Thanks

**Comment by J-a-k-o-b** [comment]
Hi @alexc-MSFT,
thank you for your help. You're right. The navigate function was in OnStart of the first site. I've now removed it and was able to enable the features again without an error.
Regards
Jakob

**Comment by alexc-MSFT** [comment]
Great glad it's working now @J-a-k-o-b - I will close this issue.
