### ISSUE TITLE
Error when launching the app from teams

### ISSUE THREAD

**Issue by BennyFeuch87** [OfficeDev/microsoft-teams-apps-requestateam#392]
### Description

When everything is set up and you try to start the Request a Team app from a test user, the error message from the screenshot always appears. Another user was used and the app was uploaded again. Unfortunately, always the same error. 

### Steps to reproduce

1. Open Teams
2. Start the Request a Team app in a Channel

### Expected results

Actually, the app should load all things and not show any error.

### Actual Results

![Bild (3)](https://user-images.githubusercontent.com/100698192/234589010-f5cc9ccb-273d-48c9-90f6-38b9f4c1dcf7.png)
![Bild (2)](https://user-images.githubusercontent.com/100698192/234589020-28860fe5-4f21-4b36-b57f-24d818585c93.png)
![Bild (1)](https://user-images.githubusercontent.com/100698192/234589023-606559c7-ded9-4fca-b44e-d34370b34dfd.png)
![Bild](https://user-images.githubusercontent.com/100698192/234589025-3341e03f-2471-4c47-8016-b91ea5d385b2.png)

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by soldier9945** [comment]
Hello @BennyFeuch87 

May I suggest having a look at [https://github.com/OfficeDev/microsoft-teams-apps-requestateam/issues/336](Issue 336)?

One of the errors I see on your screenshot has been discussed about there. The problem is Caching. You have to go to your app, go to Information and delete all the older versions but the latest. There is also a "Live" Tag on one of the versions, I don't know how this works exactly but it may be indeed a cache-and-wait type of problem.

**Comment by BennyFeuch87** [comment]
Thank you. :-) It works:
