### ISSUE TITLE
Location error when running deploy script

### ISSUE THREAD

**Issue by gblack1979** [OfficeDev/microsoft-teams-apps-requestateam#46]
Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/global-infrastructure/locations/
At C:\Apps\Teams
Request\microsoft-teams-apps-requestateam-master\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:609 char:9
+         throw "Invalid Azure Location. Please provide a valid locatio ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invalid Azure L...ture/locations/:String) [], RuntimeException
    + FullyQualifiedErrorId : Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/g
   lobal-infrastructure/locations/

For the location I have tried:
North Central US
northcentralus

Central US
centralus

**Comment by thondal-evry** [comment]
I had the same isse, but I changed mine to westeurope


Try one of these:

eastasia
southeastasia
centralus
eastus
eastus2
westus
northcentralus
southcentralus
northeurope
westeurope
japanwest
japaneast
brazilsouth
australiaeast
australiasoutheast
southindia
centralindia
westindia
canadacentral
canadaeast
uksouth
ukwest
westcentralus
westus2
koreacentral
koreasouth
francecentral
francesouth
australiacentral
australiacentral2
southafricanorth
southafricawest

**Comment by jbrdev** [comment]
I tried all eastus and eastus2, but no luck!

**Comment by jbrdev** [comment]
I have the same issue no matter what locations I typed:

You cannot call a method on a null-valued expression.
At C:\Users\brich\OneDrive - JBConsulting Group\SharePoint\Development\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:620 char:5
+     $global:location = $Location.Replace(" ","").ToLower()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/global-infrastructure/locations/
At C:\Users\brich\OneDrive - JBConsulting Group\SharePoint\Development\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:624 char:9
+         throw "Invalid Azure Location. Please provide a valid locatio ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invalid Azure L...ture/locations/:String) [], RuntimeException
    + FullyQualifiedErrorId : Invalid Azure Location. Please provide a valid location. See this list - https://azure.microsoft.com/en-gb/global-infrastructure/locations/

**Comment by alexc-MSFT** [comment]
@jbrdev @thondal-evry please can you try running the Get-AzLocation cmdlet and see what comes back? Also when passing the Location parameter to the script, are you doing this inline or when prompted? 

Thanks

**Comment by gblack1979** [comment]
When running the command Get-AzLocation it comes back blank. I am passing the parameter inline.

**Comment by jbrdev** [comment]
Hi alexc,
Thanks for getting back to us. I am passing the Location parameter when prompted. When running Get-AZLocation, a list of Azure locations come back. See picture below:

![image](https://user-images.githubusercontent.com/66507517/84101789-cb7baa00-a9dc-11ea-84e6-c79fd99affe7.png)

**Comment by alexc-MSFT** [comment]
@jbrdev thanks for this, please can you run the script with all the parameters inline, please anonymise the tenant details etc. and post on here the parameters you are using. @gblack1979 please do the same.

I'm unable to replicate it here by passing any azure location into the Location param whether inline or not e.g. east us/eastus etc.

**Comment by alexc-MSFT** [comment]
@jbrdev @gblack1979 I'm struggling to replicate this anywhere. What I'd suggest is, to get you up and running just remove the ValidateAzureLocation function from the deploy.ps1 script and remove the reference to where it is called. This should allow you to continue.

Let me know how you get on.

Thanks

**Comment by jbrdev** [comment]
@alexc-MSFT - I removed the ValidateAzureLocation function along with the reference to where it is called. However, I came across a lot of errors although I got "Deployment completed successfully". I even tried different tenant.
See below:

Creating Azure AD App - 'Request-a-team'...
az : Expecting value: line 1 column 1 (char 0)
At line:430 char:9
+         az ad app create --display-name $appName --required-resource- ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Expecting value...lumn 1 (char 0):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Waiting for app to finish creating...
Created Azure AD App
Granting admin content for Microsoft Graph...
az : az ad app permission admin-consent: error: argument --id: expected one argument
At line:445 char:9
+         az ad app permission admin-consent --id $global:appId
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (az ad app permi...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az ad app permission admin-consent [-h] [--verbose] [--debug]
                                          [--only-show-errors]
                                          [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                                          [--query JMESPATH] --id IDENTIFIER

Granted admin consent
### AZURE AD APP CREATION FINISHED ###
### TEAMS REQUESTS SITE CREATION ###
Creating Teams Requests SharePoint site...
New-PnPSite : {"error":{"code":"-1, 
System.Data.Services.Client.DataServiceClientException","message":"{\"odata.error\":{\"code\":\"Request_BadRequest\",\"message\":{\"lang\":\"en\",\"value\":\"Invalid value specified for property 
'mailNickname' of resource 'Group'.\"},\"requestId\":\"1b296534-69c9-4782-bacc-8f2efe71579f\",\"date\":\"2020-06-13T06:17:49\",\"values\":[{\"item\":\"PropertyName\",\"value\":\"mailNickname\"},{\"it
em\":\"PropertyErrorCode\",\"value\":\"InvalidValue\"}]}}"}}
At line:270 char:17
+ ...             New-PnPSite -Type TeamSite -Title $RequestsSiteName -Alia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.NewSite
Site created
**TEAMS REQUESTS SITE CREATION COMPLETE**


![image](https://user-images.githubusercontent.com/66507517/84561650-48c85700-ad1c-11ea-9549-488ae346e348.png)


### AZURE RESOURCES DEPLOYMENT ###
Starting Azure resources deployment...
Creating resource group yspgrg...
New-AzResourceGroup : Cannot validate argument on parameter 'Location'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:674 char:56
+ ... w-AzResourceGroup -Name $resourceGroupName -Location $global:location
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzResourceGroup], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupCmdlet
 
Created resource group
Creating and deploying automation assets...
Error occured while deploying Azure resources: Cannot bind argument to parameter 'Location' because it is null.
Deploying api connections...
az : [Errno 2] No such file or directory: 'connections.json'
At line:512 char:9
+         az deployment group create --resource-group $resourceGroupNam ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([Errno 2] No su...nnections.json':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Deploying logic app...
az : [Errno 2] No such file or directory: 'processteamrequestv1.0.json'
At line:521 char:13
+             az deployment group create --resource-group $resourceGrou ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([Errno 2] No su...questv1.0.json':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Finished deploying logic app
Azure resources deployed
### AZURE RESOURCES DEPLOYMENT COMPLETE ###
### LOGIC APP CONNECTIONS AUTHORISATION ###
Starting authorisation for Logic App Connections
Please authenticate with the Service Account - ben@yoursharepointguy.com
Get-AzResource : Resource group 'yspgrg' could not be found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : f13697ea-34ad-46c0-9002-8d558d321410
At line:584 char:22
+ ... onnection = Get-AzResource -ResourceType "Microsoft.Web/connections"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResource], ResourceManagerCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Get-AzResource : Resource group 'yspgrg' could not be found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 3b84b541-3bfd-4d66-854a-24b22af62b30
At line:586 char:30
+ ... onnection = Get-AzResource -ResourceType "Microsoft.Web/connections"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResource], ResourceManagerCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Get-AzResource : Resource group 'yspgrg' could not be found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 5bfbc7ce-ec03-4bbe-bdcc-cee08124d13c
At line:588 char:28
+ ... onnection = Get-AzResource -ResourceType "Microsoft.Web/connections"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResource], ResourceManagerCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Get-AzResource : Resource group 'yspgrg' could not be found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 6995182a-17b1-493e-bf4b-d2a97d5a6c5c
At line:590 char:24
+ ... onnection = Get-AzResource -ResourceType "Microsoft.Web/connections"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResource], ResourceManagerCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
SharePoint Connection
Invoke-AzResourceAction : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:556 char:87
+ ... urceAction -Action "listConsentLinks" -ResourceId $resourceId -Parame ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AzResourceAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
 
Cannot index into a null array.
At line:564 char:5
+     $code = ($uri | Select-string -pattern $regex).Matches[0].Groups[ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Get-AzResource : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:577 char:46
+     $connection = Get-AzResource -ResourceId $resourceId
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Cannot index into a null array.
At line:578 char:5
+     Write-Host "Connection " $connection.Name " now " $connection.Pro ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Office 365 Outlook Connection
Invoke-AzResourceAction : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:556 char:87
+ ... urceAction -Action "listConsentLinks" -ResourceId $resourceId -Parame ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AzResourceAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
 
Cannot index into a null array.
At line:564 char:5
+     $code = ($uri | Select-string -pattern $regex).Matches[0].Groups[ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Get-AzResource : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:577 char:46
+     $connection = Get-AzResource -ResourceId $resourceId
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Cannot index into a null array.
At line:578 char:5
+     Write-Host "Connection " $connection.Name " now " $connection.Pro ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Office 365 Users Connection
Invoke-AzResourceAction : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:556 char:87
+ ... urceAction -Action "listConsentLinks" -ResourceId $resourceId -Parame ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AzResourceAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
 
Cannot index into a null array.
At line:564 char:5
+     $code = ($uri | Select-string -pattern $regex).Matches[0].Groups[ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Get-AzResource : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:577 char:46
+     $connection = Get-AzResource -ResourceId $resourceId
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Cannot index into a null array.
At line:578 char:5
+     Write-Host "Connection " $connection.Name " now " $connection.Pro ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Microsoft Teams Connection
Invoke-AzResourceAction : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:556 char:87
+ ... urceAction -Action "listConsentLinks" -ResourceId $resourceId -Parame ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AzResourceAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
 
Cannot index into a null array.
At line:564 char:5
+     $code = ($uri | Select-string -pattern $regex).Matches[0].Groups[ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Get-AzResource : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:577 char:46
+     $connection = Get-AzResource -ResourceId $resourceId
+                                              ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Cannot index into a null array.
At line:578 char:5
+     Write-Host "Connection " $connection.Name " now " $connection.Pro ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
### LOGIC APP CONNECTIONS AUTHORISATION COMPLETE ###
DEPLOYMENT COMPLETED SUCCESSFULLY

**Comment by alexc-MSFT** [comment]
@gblack1979 that is quite a few errors, the first one indicates it has not been able to create the AD application, also the SharePoint site URL appears to be incorrect and looks as if it was specified twice.

Is this user a global admin?

**Comment by jbrdev** [comment]
yes, the user has global admin role assigned!

**Comment by jfoley22** [comment]
I am having the same problem. I have tried the steps across several computers, both on the corporate network and off. The one thing I am noticing, after it fails if I run the command Get-Azlocation it comes back blank. If then after it comes back blank, I run the command connect-azaccount, it has me log in and then I can run the command Get-AzLocation and it will pull the location. So I think the script is missing the part to log into azaccount or something.

**Comment by jbrdev** [comment]
@jfoley22 you are right! something is really not right with the script!

**Comment by alexc-MSFT** [comment]
@jfoley22  @jbrdev the script runs a Connect-AzAccount before Get-AzLocation so it will return values. If you don't connect first then yes it will come back blank. 

Given you are still stuck please can you let me know your email addresses and I will get in touch to try and get this fixed. Please note this is not being done in official Microsoft capacity and will be carried out in my own time to get you over the line.

Thanks

**Comment by jfoley22** [comment]
@alexc-MSFT I am not all that familiar with gethub, is there a way to send you a PM?

**Comment by alexc-MSFT** [comment]
@jfoley22 there is no PM feature, if you are happy to post your email address here/an email I can reach you on then I will reach out via email. Thanks

**Comment by jfoley22** [comment]
Okay, bengaldom22@gmail.com

**Comment by jbrdev** [comment]
@alexc-MSFT : Is there anything else you can do for me?

**Comment by jfoley22** [comment]
@alexc-MSFT just wondering when you might be able to reach out?

**Comment by alexc-MSFT** [comment]
> cmdlet deploy.ps1 at command pipeline position 1
> Supply values for the following parameters:
> TenantName: contoso
> TenantId: 1e5d68bd-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> RequestsSiteName: https://jbconsultinggroup.sharepoint.com/sites/Comm
> RequestsSiteDesc: "Request-a-team App"
> ManagedPath: sites
> SubscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> Location: eastus
> ResourceGroupName: JBResource
> AppName: Request-a-team
> ServiceAccountUPN:[ben@jbrinvestments.com](mailto:ben@jbrinvestments.com)

Please can you try putting all of the parameters inside speechmarks and see what happens. Thanks

**Comment by alexc-MSFT** [comment]
@jfoley22 I have sent you an email

**Comment by jbrdev** [comment]
> > cmdlet deploy.ps1 at command pipeline position 1
> > Supply values for the following parameters:
> > TenantName: contoso
> > TenantId: 1e5d68bd-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> > RequestsSiteName: https://jbconsultinggroup.sharepoint.com/sites/Comm
> > RequestsSiteDesc: "Request-a-team App"
> > ManagedPath: sites
> > SubscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> > Location: eastus
> > ResourceGroupName: JBResource
> > AppName: Request-a-team
> > ServiceAccountUPN:[ben@jbrinvestments.com](mailto:ben@jbrinvestments.com)
> 
> Please can you try putting all of the parameters inside speechmarks and see what happens. Thanks

-----------------------------------------------------------------------------------------
@alexc-MSFT I did what you asked me to, but no luck! Same result!
Has anyone successfully ran the script?

**Comment by jfoley22** [comment]
> @jfoley22 I have sent you an email

I didn't receive anything? You sure you sent it correctly? Bengaldom22@gmail.com

**Comment by alexc-MSFT** [comment]
Sorry @jfoley22 I've sent you an email now.

It's worth noting to all of you in this issue that the provided location MUST support Automation and Logic Apps. I've updated the deployment guide.

Thanks

**Comment by alexc-MSFT** [comment]
@jfoley22 @jbrdev any updates on how you are getting on? Thanks

**Comment by HarmJanNL** [comment]
I had this exact issue, couldn't find why it did not work for me but I did find a workaround and the application is succesfully running in our testenvironment.

Just define the location parameter again later on in the script, just before the "ValidateAzureLocation function. So just put $Location = "westeurope" at line 580 and it will work (location and linenumber may differ).

**Comment by alexc-MSFT** [comment]
Closing as this seems to be an old issue. If it is still a problem, please re-raise.
