### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jesslyn-omm** [OfficeDev/microsoft-teams-apps-requestateam#54]
I'm getting the below errors:

**Site Creation - Site is NOT created**
Error occured while creating of the SharePoint site: There is currently no connection yet. Use Connect-PnPOnline to connect.
Connect-PnPOnline : Invalid URI: The hostname could not be parsed.
At C:\Users\Jesslyn\Desktop\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:649 char:15
+ $pnpConnect = Connect-PnPOnline $requestsSiteUrl -UseWebLogin
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline
 
THEN
Connect-PnPOnline : Invalid URI: The hostname could not be parsed.
At C:\Users\Jesslyn\Desktop\microsoft-teams-apps-requestateam-master\Deployment\Scripts\deploy.ps1:642 char:15
+ $pnpConnect = Connect-PnPOnline -Url $tenantAdminUrl -UseWebLogin
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

Notes on above. - Would this have anything to do with our company name having an apostrophe?

**Comment by alexc-MSFT** [comment]
@jesslyn-omm yes I think you are right in terms of it being to do it with apostrophe.

This is because the tenant name you pass into the script is used to form the SharePoint admin center URL and also the URL for the requests site.

Out of interest, is the domain name used in your SharePoint tenant URL different from the one configured in O365/Azure AD? I think the answer will be yes i.e. the URL will not have the apostrophe.

If this is the case, just enter the domain used in the SharePoint admin center URL instead e.g. if my admin center url was https://contoso-admin.sharepoint.com then I would just use the 'contoso' part.

Hope that makes sense?

We will consider renaming the parameter so it makes more sense.

Thanks

**Comment by jesslyn-omm** [comment]
I fixed by changing the tenant name.  Thank you

**Comment by alexc-MSFT** [comment]
No probs @jesslyn-omm . Going to keep this issue open and link it to a new one to update the documentation.
