### ISSUE TITLE
Issue when checking if team exists upon team creation

### ISSUE THREAD

**Issue by BenVdP** [OfficeDev/microsoft-teams-apps-requestateam#97]
Hi,

When I try to check the availablity of a team, I see this error and cannot proceed to the next step.

`CheckTeamAvailability.Run failed: { "error": { "code": 502, "source": "europe-002.azure-apim.net", "clientRequestId": "9e6dddd0-6a44-48f2-9e05-46b30c3d9058", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not received a response from an upstream server. Request tracking id '08586060007104963070247685370CU132'." } } } }`

**Comment by alexc-MSFT** [comment]
@BenVdP did you edit the SharePoint actions inside the Flow and update these to point at your SharePoint site?

Thanks

**Comment by FernandoGualano** [comment]
Hi! I had the same issue. The problem was I didn't modify the List Name under Check Team Availability Flow > Check site exists response > Check for existing requests matching URL. The Deployment Guide say:

![image](https://user-images.githubusercontent.com/50090959/99989189-16258e80-2d91-11eb-9b2a-927a03d8fca4.png)

But it doesn't say anything about modifying the "List Name" field. This field must be replaced by "Teams Requests", that is the List Name. 

I hope it helps! Thanks!

**Comment by alexc-MSFT** [comment]
@BenVdP please follow @FernandoGualano 's comment and this will fix it.

Closing for now.
